eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-3-7-66-173.ap-south-1.compute.amazonaws.com:8761/eureka
    instance:
    preferIpAddress: true
    register-with-eureka: false
    fetch-registry: true
#spring:
#  application:
#    name: micro-serv1

spring:
  main:
    web-application-type: reactive
  application:
    name: micro-serv1

app:
  other:
    dbserv: http://ec2-52-66-250-235.ap-south-1.compute.amazonaws.com:8090/hello/first




